spring.application.name=Applivo

spring.datasource.url=jdbc:mysql://localhost:3306/applivo
spring.datasource.username=ash.applivo
spring.datasource.password=applivo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.jpa.hibernate.ddl-auto=validate

server.port=8080

jwt.secret=CpyEj3olBV5PIVQbF2vt8dSvSHHhhdCBXG5/7W0SZ/w=
jwt.expiration=900000
jwt.refresh-expiration=604800000

storage.base-upload-path=./uploads
storage.max-file-size-mb=100
storage.allowed-extensions=.apk

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=105MB

emulator.docker-image=budtmo/docker-android:emulator_13.0
emulator.boot-timeout-seconds=420
emulator.max-concurrent-sessions=5
emulator.screenshot-android-path=/data/local/tmp/screen.png
emulator.screenshot-container-path=/tmp/screen.png
emulator.base-console-port=5554
emulator.base-adb-port=5555
emulator.base-vnc-port=6080